language: python

addons:
    apt:
        packages:
            - enscript

python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3

install:
    - pip install tox-travis

script:
    - tox

notifications:
    email: false
